# Generated by Django 4.2.11 on 2024-05-02 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariantprice',
            name='product_variant_one',
        ),
        migrations.RemoveField(
            model_name='productvariantprice',
            name='product_variant_three',
        ),
        migrations.RemoveField(
            model_name='productvariantprice',
            name='product_variant_two',
        ),
        migrations.AddField(
            model_name='productvariantprice',
            name='product_variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_variant', to='product.productvariant'),
        ),
    ]
